---
site_name: Truffle
repo_url: https://github.com/Consensys/truffle
site_description: Truffle Documentation
theme: readthedocs
pages:
- Introduction: 'index.md'
- Getting Started:
  - Installation: 'getting_started/installation.md'
  - Choosing an Ethereum client: 'getting_started/client.md'
  - Creating a project: 'getting_started/project.md'
  - Compiling your contracts: 'getting_started/compile.md'
  - Deploying to the network: 'getting_started/deploy.md'
  - Building your frontend: 'getting_started/build.md'
  - Writing tests: 'getting_started/tests.md'
  - Interacting with your contracts: 'getting_started/contracts.md'
- Advanced:
  - Configuration: 'advanced/configuration.md'
  - Environments: 'advanced/environments.md'
  - Deployment Options: 'advanced/deploy.md'
  - Build Processes: 'advanced/build.md'
  - Command Reference: 'advanced/commands.md'
